# frozen_string_literal: true
require 'fileutils'

task :build do
  sh 'stack build'
  FileUtils.mkdir 'bin' unless File.exist? 'bin'
  FileUtils.cp `stack exec which seiji-tools`.chomp, 'bin/', preserve: true
end

task :test do
  sh 'rubocop'
  sh 'cucumber'
  sh 'stack test'
end
